# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(PipelineVariable)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - bash: ls -R $(Build.ArtifactStagingDirectory)
  


    
# - stage: DevDeploy
#   dependsOn: Build
#   variables :
#     environment: Dev
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - script: echo Deploying to $(environment) Environment

# - stage: QADeploy
#   dependsOn: Build
#   variables:
#     environment: QA
#   jobs:
#   - job: QADeployJob
#     steps:
#     - script: echo Deploying to $(environment) Environment

# - stage: ProdDeploy
#   dependsOn: 
#   - DevDeploy
#   - QADeploy
#   variables:
#     environment: prod
#   jobs:
#   - job: ProdDeploy
#     steps: 
#     - bash: echo Deploying to $(environment) Environment

