# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

# Pipelines > Stages > Jobs > Task(Steps)

jobs:

- job: job1
  steps:
  - script: echo job1
    displayName: 'Run job1'

- job: job2
  steps:
  - script: echo job2
    displayName: 'Run job2'
