# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

# Pipelines > Stages > Jobs > Task(Steps)

jobs:

- job: job1
  steps:
  - script: echo job1 executing
    displayName: 'JOB1'

- job: job2
  dependsOn: job2
  steps:
  - script: echo job2 executing
    displayName: 'JOB2'

- job: job3
  dependsOn: job1
  steps:
  - script: echo job3 executing
    displayName: 'JOB3'

